version: 2
formats: []

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs