name: Lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Pyright on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          pip install .[tests,pip]
          pip install pyright
      
      - name: Run pyright
        id: run-pyright
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          pyright --pythonversion ${{ matrix.python-version }} --warnings

  ruff:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Ruff on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          pip install .[tests,pip]
          pip install ruff
      
      - name: Run Ruff Linter
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        uses: astral-sh/ruff-action@v3