name: Run Tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install -e .[tests,pip]

      - name: Run Tests
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          python -m pytest
      
      - name: Generate Coverage Badge
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg

      - name: Upload Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge-${{ matrix.python-version }}.svg
          path: coverage.svg

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report_${{ matrix.python-version }}
          path: htmlcov
          include-hidden-files: true
  
  publish-coverage-report:
    runs-on: ubuntu-latest
    needs: run-tests

    name: Publish Coverage Report
    steps: 
      - name: Checkout Coverage Branch
        uses: actions/checkout@v4
        with:
          ref: coverage-report

      - name: Download Artifacts
        uses: actions/download-artifact@v4
      
      - name: Show Tree
        run: |
          find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      
      - name: Commit Artifacts
        continue-on-error: true
        run: |
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto Update Coverage Report"
          git push