name: Run Tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install -e .[tests,pip]

      - name: Run Tests
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          python -m pytest
      
      - name: Generate Coverage Badge
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg

      - name: Upload Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge-${{ matrix.python-version }}.svg
          path: coverage.svg

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report_${{ matrix.python-version }}
          path: htmlcov
          include-hidden-files: true
  
  publish-coverage-report:
    runs-on: ubuntu-latest
    needs: run-tests

    name: Publish Coverage Report
    steps: 
      - name: Checkout Coverage Branch
        uses: actions/checkout@v4
        with:
          ref: coverage-report

      - name: Set up CPython 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Delete Old Reports
        run: |
          rm -r -v -f coverage*
          rm -r -v -f badges
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Delete old reports" --allow-empty

      - name: Download Artifacts
        uses: actions/download-artifact@v5

      - name: Run Scripts
        run: |
          cd .scripts
          pip install -r requirements.txt
          python update_dirs.py
          python update_badges.py
          python remove_nested_gitignores.py

      - name: Commit New Artifacts
        run: |
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Download new reports" --allow-empty
      
      - name: Show Tree
        run: |
          find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Commit Artifacts
        continue-on-error: true
        run: |
          git reset --soft HEAD~2
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto Update Coverage Report"
          git push