name: Test Workflow

on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest

    name: Checkout
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump vars context
        env:
            VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}"