name: Run Tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -U -r requirements.txt
          pip install -U -r requirements-tests.txt

      - name: Run Tests
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          python -m pytest